// Local, original Mochiichao sprites (generated by tools/sprites/build.py).
// No external sprite API is used anywhere: every sprite is a file under
// public/sprites/mochiichao/{front,back}/<slug>.png served with the app.
import { SPRITE_SLUG_BY_ID, SPRITE_SLUG_BY_NAME } from './spriteManifest';

export type SpriteView = 'front' | 'back';

const norm = (s: string) => s.toLowerCase().replace(/[\s-]/g, '');

/** Resolve a species to its sprite slug. Name wins over id, because some game
 *  data reuses ids for other species (see docs/SPECIES.md "data conflicts"). */
export function spriteSlug(opts: { id?: string | number | null; name?: string | null; slug?: string | null }): string | null {
  if (opts.slug) return opts.slug;
  if (opts.name) {
    const byName = SPRITE_SLUG_BY_NAME[norm(opts.name)];
    if (byName) return byName;
  }
  if (opts.id !== undefined && opts.id !== null) {
    const id = String(opts.id);
    return SPRITE_SLUG_BY_ID[id] ?? SPRITE_SLUG_BY_ID[id.padStart(3, '0')] ?? null;
  }
  return null;
}

export function spriteUrl(slug: string, view: SpriteView = 'front'): string {
  const base = (import.meta as any).env?.BASE_URL ?? '/';
  return `${base}sprites/mochiichao/${view}/${slug}.png`;
}
