"""Build the original Mochiichao sprite set.

python3 tools/sprites/build.py
  -> public/sprites/mochiichao/front/<slug>.png   (96x96 RGBA, <=16 colours + transparency)
  -> public/sprites/mochiichao/back/<slug>.png
  -> src/lib/spriteManifest.ts                    (id/name -> slug lookup, generated)
  -> docs/SPECIES.md                              (merged species table, generated)
  -> proof/contact_sheet.png                      (all sprites, front + back)
"""
import json, os, sys
from PIL import Image, ImageDraw, ImageFont
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, HERE)
from pixelkit import Sprite, flip
from designs import DESIGNS
from species_table import SPECIES, slug, lines

MAXC = 16
OUT = os.path.join(ROOT, 'public', 'sprites', 'mochiichao')

def limit(img):
    cols = img.getcolors(1 << 16)
    opaque = [c for c in cols if c[1][3] > 0]
    if len(opaque) <= MAXC: return img, len(opaque)
    a = img.split()[3]
    q = img.convert('RGB').quantize(MAXC, method=Image.Quantize.MAXCOVERAGE).convert('RGB')
    q.putalpha(a.point(lambda v: 255 if v else 0))
    return q, len([c for c in q.getcolors(1 << 16) if c[1][3] > 0])

def render(sid, back):
    s = Sprite(); DESIGNS[sid](s, back)
    img = s.render()
    if back: img = flip(img)
    return limit(img)

def main():
    os.makedirs(os.path.join(OUT, 'front'), exist_ok=True); os.makedirs(os.path.join(OUT, 'back'), exist_ok=True)
    report, imgs = [], {}
    for sp in SPECIES:
        sid, sl = sp['id'], slug(sp['name'])
        f, nf = render(sid, False); b, nb = render(sid, True)
        f.save(os.path.join(OUT, 'front', sl + '.png'), optimize=True)
        b.save(os.path.join(OUT, 'back', sl + '.png'), optimize=True)
        imgs[sid] = (f, b)
        report.append(dict(id=sid, name=sp['name'], slug=sl, front_colors=nf, back_colors=nb))
    # manifest
    by_id = {sp['id']: slug(sp['name']) for sp in SPECIES}
    by_name = {}
    for sp in SPECIES:
        for n in [sp['name']] + sp['aliases']:
            by_name[n.lower().replace(' ', '').replace('-', '')] = slug(sp['name'])
    # names used in game data that point at another id's species (see docs/SPECIES.md "data conflicts")
    ts = ['// GENERATED by tools/sprites/build.py - do not edit by hand.',
          '// Original Mochiichao sprites live in public/sprites/mochiichao/{front,back}/<slug>.png',
          f'export const SPRITE_SLUG_BY_ID: Record<string, string> = {json.dumps(by_id, indent=2)};',
          f'export const SPRITE_SLUG_BY_NAME: Record<string, string> = {json.dumps(by_name, indent=2)};', '']
    open(os.path.join(ROOT, 'src', 'lib', 'spriteManifest.ts'), 'w').write('\n'.join(ts))
    json.dump(report, open(os.path.join(ROOT, 'proof', 'sprite_report.json'), 'w'), indent=1)
    json.dump([dict(id=sp['id'], name=sp['name'], elements=sp['elements'], slug=slug(sp['name'])) for sp in SPECIES],
              open(os.path.join(ROOT, 'proof', 'harness', 'species.json'), 'w'), indent=1)
    write_doc()
    contact_sheet(imgs)
    print(len(report), 'species;', 'max colours front/back:', max(r['front_colors'] for r in report), max(r['back_colors'] for r in report))

def write_doc():
    by = {s['id']: s for s in SPECIES}
    L = ['# Mochiichao species table (merged)', '',
         'Generated by `tools/sprites/build.py` from `tools/sprites/species_table.py`.',
         'Sources: ST = src/lib/species.ts, GR = src/lib/global_roster.json, GD = src/world/GameData.ts, '
         'MD = Drive mochiichao-diamond.jsx, BS = Drive MochiichaoBattleSystem.jsx, WM = Drive mochiichao-world-map.jsx, '
         'DIW = Dream-Infinite-World MochiichaoCanvas.tsx.', '',
         f'**{len(SPECIES)} species** ({sum(1 for s in SPECIES if s["id"][0].isdigit())} with global ids, '
         f'{sum(1 for s in SPECIES if not s["id"][0].isdigit())} from the Drive battle prototype / Dream-Infinite-World).', '',
         '| ID | Name | Elements (GR) | Game types (ST) | Other types | Description | Colors | Evolution | Sprite | Sources |',
         '|---|---|---|---|---|---|---|---|---|---|']
    for s in SPECIES:
        evo = []
        if s['evolves_from']: evo.append(f"from {by[s['evolves_from']]['name']}")
        if s['evolves_to']: evo.append(f"to {by[s['evolves_to'][0]]['name']} @ Lv{s['evolves_to'][1]}")
        nm = s['name'] + (f" (aka {', '.join(s['aliases'])})" if s['aliases'] else '')
        L.append(f"| {s['id']} | {nm} | {'/'.join(s['elements'])} | {'/'.join(s['types_game']) or '-'} | {'/'.join(s['alt_types']) or '-'} | "
                 f"{s['description']} | {' '.join('`'+c+'`' for c in s['colors'])} | {'; '.join(evo) or '-'} | "
                 f"`{slug(s['name'])}.png` | {', '.join(s['sources'])} |")
    L += ['', '## Evolution lines', '']
    for ln in lines():
        L.append('- ' + ' -> '.join(f"{by[i]['name']} ({i})" for i in ln))
    L += ['', '## Data conflicts found while merging (left unchanged in game data)', '',
          '- 005 is `Chromedile` in species.ts but `Chromejaww` in global_roster.json (both names map to the same sprite).',
          '- species.ts keys Dreadtoise as 039 (Sproutle -> Dreadtoise @18); global_roster.json has 039 Shellguard -> 040 Dreadtoise. '
          'The sprite resolver looks up by species *name* first, so the game\'s "039 Dreadtoise" shows the Dreadtoise sprite.',
          '- species.ts only defines 12 species (001-010, 038, 039); global_roster.json lists 47 (001-046 + 331).',
          '- Types differ by source (e.g. Kittember FIRE in species.ts, Umbral in the Drive docs; Tyrage GROUND vs FLAME in BS). All are kept above.',
          '- Drive docs use their own numbering (Squirmite 042, Zephling 055, Pupbble 067, Gearkid 082, Dreadtoise 099; BS uses 1-10).',
          '- FullWorldMaps.ts: route encounter `{id:"016", name:"Zephling"}` (016 is Squirmite in GR) and Bug Catcher Rick\'s '
          '`{id:"004", name:"Squirmite"}`; name-first lookup shows the named creature.',
          '- global_roster.json is not valid JSON (entry 002 has `"atk: 63`); it is not imported by the game.', '']
    os.makedirs(os.path.join(ROOT, 'docs'), exist_ok=True)
    open(os.path.join(ROOT, 'docs', 'SPECIES.md'), 'w').write('\n'.join(L))

def contact_sheet(imgs):
    cols, cell, sc = 6, 2 * 96 * 1 + 24, 1
    rows = (len(SPECIES) + cols - 1) // cols
    cw, ch = 2 * 96 + 16, 96 + 34
    sheet = Image.new('RGBA', (cols * cw + 16, rows * ch + 56), (16, 22, 34, 255))
    d = ImageDraw.Draw(sheet)
    try: font = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf', 12); big = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf', 18)
    except Exception: font = big = ImageFont.load_default()
    d.text((12, 12), f'Original Mochiichao sprites - {len(SPECIES)} species, front | back (96x96, <=16 colours)', fill=(45, 255, 210), font=big)
    for i, sp in enumerate(SPECIES):
        x, y = 8 + (i % cols) * cw, 48 + (i // cols) * ch
        d.rectangle([x, y, x + cw - 6, y + ch - 6], fill=(10, 15, 24, 255), outline=(30, 60, 70, 255))
        f, b = imgs[sp['id']]
        sheet.alpha_composite(f, (x + 2, y + 2)); sheet.alpha_composite(b, (x + 98, y + 2))
        d.text((x + 6, y + 100), f"{sp['id']} {sp['name']}", fill=(220, 240, 255), font=font)
        d.text((x + 6, y + 113), '/'.join(sp['elements']), fill=(120, 160, 180), font=font)
    sheet.save(os.path.join(ROOT, 'proof', 'contact_sheet.png'))
    # 2x line sheet (evolution lines side by side) for easier review
    by = {s['id']: s for s in SPECIES}
    ls = lines(); w = max(len(l) for l in ls)
    lsheet = Image.new('RGBA', (w * 200 + 20, len(ls) * 200 // 2 + 20), (16, 22, 34, 255))
    dd = ImageDraw.Draw(lsheet)
    for r, ln in enumerate(ls):
        for c, sid in enumerate(ln):
            im = imgs[sid][0]
            lsheet.alpha_composite(im, (10 + c * 200, 10 + r * 100))
            dd.text((110 + c * 200, 40 + r * 100), by[sid]['name'], fill=(220, 240, 255), font=font)
    lsheet.save(os.path.join(ROOT, 'proof', 'evolution_lines.png'))

if __name__ == '__main__':
    main()
